version: '3.8'

services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # MongoDB
  mongodb:
    image: mongo:6
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI App
  app:
    build: .
    container_name: chat-app
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_DB: chatdb
      REDIS_URL: redis://redis:6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - chat-network
    volumes:
      - ./app:/app/app  # Para desenvolvimento
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  chat-network:
    driver: bridge

volumes:
  redis-data:
  mongo-data: